config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only:[:index, :show, :new, :create,:edit,:update] 

  get 'users/:id/thanks', to: 'users#thanks'  
  
  resources :questions,only:[:show, :new, :destroy,:create]  do
    resources :answers, only: [:create,] 
  end

  
  resources :thanks, only: [:create, :destroy,]

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  
  validates :content,presence: true,length:{maximum: 400}
  
  has_many :thanks,dependent: :destroy
  has_many :thank_users,through: :thanks,source: :user
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  
  validates :title,presence: true,length:{maximum: 50}
  validates :content,presence: true,length:{maximum: 400}
  
  has_many :answers,dependent: :destroy
  has_many :answer_users,through: :answers,source: :user,dependent: :destroy
  
  def thanks?(answer)
    self.user.thank_answers.include?(answer)
  end
  
end

app/models/thank.rb
class Thank < ApplicationRecord
  belongs_to :user
  belongs_to :answer
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true,length:{maximum: 50}
  validates :introduce, presence: true,length:{maximum: 255}
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :questions
  has_many :answers,dependent: :destroy
  has_many :answer_questions,through: :answers,source: :question
  has_many :thanks
  has_many :thank_answers,through: :thanks,source: :answer
  
  
  
  def thank(answer,question)
    thanks.find_or_create_by(answer_id: answer.id,question_id: question.id)
  end
  
  
  def unthank(answer,question)
    thank = self.thanks.find_by(answer_id: answer.id,question_id: question.id)
    thank.destroy if thank
  end
  
  def thank_answers?(answer)
    self.thank_answers.include?(answer)
  end


  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params)
    @answers = @question.answers.order(id: :desc).page(params[:page])
    @answer.user_id = current_user.id
    if @answer.save
      flash[:success]="回答を送信しました"
      redirect_to @question
    else
      flash[:danger]="回答を送信できませんでした"
      render template: "questions/show"
    end
  end

  private
  def answer_params 
    params.require(:answer).permit(:content)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user,only:[:destroy]
  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(id: :desc).page(params[:page]).per(10)
    @answer = @question.answers.build
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      flash[:success] = "Questionを投稿しました"
      redirect_to root_url
    else
      flash[:danger] = "Questionを投稿できませんでした"
      render :new
    end
  end

  def destroy
    @question.destroy
    flash[:success] = '質問を削除しました。'
    redirect_back(fallback_location: root_path)    
  end
  
  
  
  private
  def question_params 
    params.require(:question).permit(:title,:content)
  end
  
  def correct_user
    @question = current_user.questions.find_by(id: params[:id])
    unless @question
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email=params[:session][:email].downcase
    password=params[:session][:password]
    if login(email,password)
      flash[:success]="ログインしました"
      redirect_to @user
    else
      flash[:danger]="ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session[:user_id]=nil
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end
  
  private

  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
    
  end
end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    answer=Answer.find(params[:answer_id])
    question=Question.find_by(id: answer.question_id)
    unless answer.user_id==current_user.id
      current_user.thank(answer,question)
      flash[:success]='Thanks!!'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = "自分の回答にはThanksできません"
      redirect_back(fallback_location: root_path)
    end 
  end

  def destroy
    answer=Answer.find(params[:answer_id])
    question=Question.find_by(id: answer.question_id)
    unless answer.user_id==current_user.id
      current_user.unthank(answer,question)
      flash[:danger]="Not Thanks"
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController

  def index
    if logged_in?
      @questions = Question.order(id: :desc).page(params[:page]).per(5)
      
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in,only:[:index,:show,:edit,:update,:thank]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
    @questions = @user.questions.order(id: :desc).page(params[:page]).per(5)

    #count
    answers=@user.answers
    @thanks_count=Thank.where(answer_id: answers).count
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success]='ユーザーを登録しました'
      redirect_to @user
    else
      flash[:danger] = "ユーザー登録できませんでした"
      render :new
    end
  end

  def edit
    @user=current_user
  end

  def update
    @user=current_user
    if @user.update(user_params)
      flash[:success]='変更しました'      
      redirect_to @user
    else
      flash[:danger]="失敗しました"
      render :edit
    end
  end
  
  def thanks
    @user=User.find(params[:id])
    thanks=Thank.where(answer_id: @user.answers)
    q_id=thanks.pluck(:question_id).uniq
    @questions=Question.where(id: q_id)
  end

  
  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:introduce)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type,message|%>
  <div class="alert alert-<%=message_type%>"><%=message%></div>
<%end%>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <a class="navbar-brand" href="/">Q space</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <%if logged_in?%>
          <li class="nav-item"><%= link_to '質問する', new_question_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'マイページ', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path,method: :delete%></li>
            </ul>
          </li>         
        
        <%else%>
          <li class="nav-item"><%=link_to 'Signup',signup_path,class:"nav-link"%></li>
          <li class="nav-item"><%=link_to 'Login',login_path, class:'nav-link'%></li>
        <%end%>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Q Space</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>
    
  <body>
    <%= render 'layouts/navbar'%>
    
    <div class="container">
      <%= render 'layouts/flash_messages'%>
      <%= yield %> 
    </div>
  </body>
</html>

app/views/questions/_questions.html.erb
<h2 class="text-center mt-5">みんなの質問</h2>

<ul>
  <% questions.each do |q|%>
    <li class="card mt-2">
      <div class="d-flex flex-row card-body">
        <div class="col-3 text-center">
          <img class="mr-2 rounded" src="<%= gravatar_url(q.user, { size: 50 }) %>" alt="">
          <p class="mt-3"><%=link_to q.user.name,user_path(q.user.id)%></p>
        </div>
        <div class="col-9">
          <h5 style="word-wrap: break-word"><%=link_to q.title,question_path(q),class:"shadow-sm p-3 bg-light rounded stretched-link d-block"%></h5>
          <div class="mt-3 text-right">
            <p class="">回答数：<%=q.answers.count%></p>
          </div>
        </div>      
      </div>
    </li>
  <%end%>
  <%=paginate questions%>
</ul>

app/views/questions/new.html.erb
<div class="mt-5">
  <span class="shadow-sm p-3 mb-5 mt-5 bg-light rounded">質問フォーム</span>
</div>

<div class="mt-5">
  <div>
    <p><%=current_user.name%>さん</p>
    <%= form_with(model: @question,local: true) do |f|%>
    <%= render 'layouts/error_messages',model: f.object%>
      <div class="form-group">
        <%= f.label :title, '質問タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group mt-4">
        <%= f.label :content, '質問内容' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <div class="form-group mt-4">
        <%= f.submit '投稿する', class: 'btn btn-outline-primary' %>
      </div>
    <%end%>
  </div>
</div>

app/views/questions/show.html.erb
<div class="card mr-4 ml-4">
  <div class="d-flex flex-row card-body">
    <div class="col-3 text-center">
      <img class="rounded" src="<%= gravatar_url(@question.user, { size: 50 }) %>" alt="">
      <p class="mt-4"><%=link_to @question.user.name,user_path(@question.user)%></p>
    </div>
    <div class="col-9">
      <p class="shadow-sm p-3 bg-light rounded align-baseline">Questionタイトル：  <%=@question.title%></p>
      <p class="" style="word-wrap: break-word"><%=simple_format(@question.content)%></p>
    </div>
  </div>
</div>

<div class="mt-5">
  <span class="shadow-sm p-3 mb-5 mt-5 bg-light rounded">回答一覧</span>

  <div class="mt-4">
    <% @answers.each do |answer| %>
      <div class="border ml-5 mr-5 p-3 row">
        <div class="col-3 text-center">
          <img class="rounded" src="<%= gravatar_url(answer.user, { size: 50 }) %>" alt="">
          <p class="mt-4"><%=answer.user.name%></p>
        </div class="col-9">
        <div class="col-9 ">
          <span style="word-wrap: break-word"><%= simple_format(answer.content) %></span>
          <div class="mt-4 text-right">
            <%if @question.user_id == current_user.id%>
              <%=render 'thanks/thanks',answer: answer%>
            <% elsif @question.thanks?(answer)%>
              <span class="border border-primary rounded p-1 ">Thanks</span>
            <%end%>             
          </div>
        </div>
      </div>
    <% end %>
    <%=paginate @answers%>
  </div>
  
  <%unless @question.user_id == current_user.id%>  
    <div class="mt-5">
      <span class="shadow-sm p-3 bg-light rounded">回答フォーム</span>
      <div class="mt-4 ml-5 mr-5">
        <%=form_with(model: [@question,@answer],local: true) do |f|%>
        <%= render 'layouts/error_messages',model: f.object%>
          <%= hidden_field_tag :question_id, @question.id %>
          <%= f.text_area :content,class: 'form-control'%>
          <%= f.submit '回答する', class: 'btn btn-outline-primary mt-4' %>
        <%end%>        
      </div>
    </div>
  <%end%>
  
</div>

app/views/thanks/_thanks.html.erb
<% if current_user.thank_answers?(answer) %>
  <%= form_with(model: current_user.thanks.find_by(answer_id: answer.id), local: true, method: :delete) do |f| %>
    <%= hidden_field_tag :answer_id, answer.id %>
    <%= f.submit 'thank解除', class: 'btn btn-danger btn-sm' %>
  <% end %>
<% else %>
  <%= form_with(model: current_user.thanks.build, local: true) do |f| %>
    <%= hidden_field_tag :answer_id, answer.id %>
    <%= f.submit 'thank', class: 'btn btn-primary btn-sm' %>  
  <% end %>
<% end %>

app/views/toppages/index.html.erb
<% if logged_in?%>
  <div>
    <div class="d-flex justify-content-around">
      <p><%=link_to 'あなたも質問してみよう!','questions/new',class:"btn btn-outline-primary font-weight-bold pl-4 pr-4"%></p>
      <p><%= link_to 'ユーザー一覧',users_path,class:"btn btn-outline-primary"%></p>
    </div>
    <%=render 'questions/questions',questions: @questions %>
  </div>
<%else%>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Q Space</h1>
    </div>
    
    <div class="text-center mt-4">
      <h1>Q Spaceをはじめよう！</h1>
      <h1><%=link_to'Signup!',signup_path%></h1>
    </div>
  </div>
<%end%>

app/views/users/_introduces.html.erb
<div class="row mt-3">
  <p class="shadow-sm p-3 mb-3 mt-3 bg-light rounded text-center h6"><%=@user.name%><span class="ml-2">'s  ページ</span></p>
  <div class="col-sm-10 offset-sm-1 d-flex d-row">
    <div class="col-3 text-center">
      <img class="rounded" src="<%= gravatar_url(@user, { size: 75 }) %>" alt="">
    </div>
    <div class="col-9">
      <p class="font-weight-bold">自己紹介</p>
      <p class="" style="word-wrap: break-word"><%=simple_format(@user.introduce)%></p>
      <p>総サンクス：<%=@thanks_count%></p>
    </div>
  </div>
</div>
<div class="d-flex justify-content-around mr-3 ml-3 mt-4 mb-5">
  <p><%=link_to 'プロフィール変更',edit_user_path(@user),class:"btn btn-outline-primary" if @user==current_user%> </p>
  <p><%=link_to 'Thanks一覧',"/users/#{params[:id]}/thanks",class:"btn btn-outline-primary"%></p> 
</div>

app/views/users/_users.html.erb
<% if users.any?%>
  <div>
    <span class="shadow-sm p-3 bg-light rounded">ユーザー一覧</span>
  </div>
  <div class="row">
    <div class="col-sm-10 offset-sm-1">
      <ul>
        <% users.each do |user|%>
          <li class="media border mt-4 p-3">
            <img class="mr-2 rounded d-flex mr-3" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
            <div class="media-body">
              <h5><%= user.name%></h5>
              <div>
                <p><%=user.introduce %></p>
                <p><%= link_to 'プロフィールへ',user_path(user)%></p>
              </div>
            </div>
          </li>
        <%end%>
      </ul>
      <%=paginate users%>      
    </div>
  </div>
<%end%>

app/views/users/edit.html.erb
<div>
  <span class="shadow-sm p-3 mb-5 mt-5 bg-light rounded">プロフィール変更</span>
</div>
<div>
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages',model: f.object%>
      
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>      
      <div class='form-group'>
        <%= f.label :introduce, '自己紹介'%>
        <%= f.text_area :introduce, class:"form-control"%>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'メール' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>      
      <%= f.submit '変更する', class: 'btn btn-outline-primary' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users/users', users: @users%>

app/views/users/new.html.erb
<div　class="text-center">
  <span class="shadow-sm p-3 mb-5 mt-5 bg-light rounded">Q SpaceにSign upする</span>
</div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages',model: f.object%>
      
      
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class='form-group'>
        <%= f.label :introduce, '自己紹介'%>
        <%= f.text_area :introduce, class:"form-control"%>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'メール' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <%= render 'users/introduces'%>
</div>
<div class="bor">
  <div class="mt-5 mb-4">
    <span class="shadow-sm p-3 bg-light rounded">質問一覧</span>
  </div>
  <div class="row">
    <ul class="col-10 offset-1">
       <%@questions.each do |question|%>
         <li class="card mt-3">
           <div class="card-header">
             <span>タイトル：  <%=link_to question.title,question_path(question)%><span>
           </div>
           <div class=card-body>
             <p>内容</p>
             <p class="card-text" style="word-wrap: break-word">
               <%=simple_format(question.content)%>
             </p>
             <div class="float-right mt-2">
               <span>回答数：<%=question.answers.count%></span>
               <span class="ml-5"><%=link_to '削除する',question,method: :delete,data: { confirm: '本当に削除してよろしいですか？' } if @user == current_user%></span>
             </div>
           </div>
         </li>
      <%end%>
    </ul>
  </div>
</div>

app/views/users/thanks.html.erb
<div class="mb-4">
  <span class="shadow-sm p-3 bg-light rounded">Thanks一覧</span>
</div>

<div class="mt-5 ml-4 mr-4">
  <div class="mr-5 ml-5">
    <%@questions.each do |question|%>
      <div class="row border mt-3 text-center">
        <div class="col-9 border-right">
          <%=link_to question.title,question_path(question)%>
        </div>
        <div class="col-3">
          <%=link_to question.user.name,user_path(question.user.id)%>
        </div>
      </div>
    <%end%>
  </div>
</div>